<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\WkTekkom;

class WkTekkomSeeder extends Seeder
{
    public function run(): void
    {
        $tekkomData = [
            [
                'area_id' => 'BRAVO',
                'name' => 'BRAVO',
                'position_x' => 50.82,
                'position_y' => 61.47,
                'color' => '#EF4444',
                'description' => 'Area pengeboran BRAVO. Lokasi strategis untuk eksplorasi dan produksi hidrokarbon di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform BRAVO', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '5,200 BOPD',
                'status' => 'Operasional',
                'wells' => 12,
                'depth' => '3,450 m',
                'pressure' => '2,850 psi',
                'temperature' => '85°C',
                'order' => 1,
            ],
            [
                'area_id' => 'UNIFORM',
                'name' => 'UNIFORM',
                'position_x' => 58.83,
                'position_y' => 72.58,
                'color' => '#10B981',
                'description' => 'Area pengeboran UNIFORM. Fasilitas modern dengan teknologi terkini untuk optimalisasi produksi di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform UNIFORM', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '4,800 BOPD',
                'status' => 'Operasional',
                'wells' => 10,
                'depth' => '3,200 m',
                'pressure' => '2,650 psi',
                'temperature' => '78°C',
                'order' => 2,
            ],
            [
                'area_id' => 'ECHO',
                'name' => 'ECHO',
                'position_x' => 62.36,
                'position_y' => 57.47,
                'color' => '#F59E0B',
                'description' => 'Area pengeboran ECHO. Lokasi produksi dengan potensi hidrokarbon tinggi di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform ECHO', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '6,100 BOPD',
                'status' => 'Operasional',
                'wells' => 14,
                'depth' => '3,650 m',
                'pressure' => '3,100 psi',
                'temperature' => '92°C',
                'order' => 3,
            ],
            [
                'area_id' => 'FOXTROT',
                'name' => 'FOXTROT',
                'position_x' => 69.52,
                'position_y' => 66.62,
                'color' => '#8B5CF6',
                'description' => 'Area pengeboran FOXTROT. Fasilitas produksi terintegrasi dengan sistem monitoring canggih di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform FOXTROT', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '5,500 BOPD',
                'status' => 'Operasional',
                'wells' => 11,
                'depth' => '3,380 m',
                'pressure' => '2,900 psi',
                'temperature' => '88°C',
                'order' => 4,
            ],
            [
                'area_id' => 'GG',
                'name' => 'GG',
                'position_x' => 34.41,
                'position_y' => 43.06,
                'color' => '#EC4899',
                'description' => 'Area pengeboran GG. Lokasi eksplorasi dan produksi dengan infrastruktur lengkap di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform GG', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '4,300 BOPD',
                'status' => 'Operasional',
                'wells' => 9,
                'depth' => '3,100 m',
                'pressure' => '2,550 psi',
                'temperature' => '75°C',
                'order' => 5,
            ],
            [
                'area_id' => 'LIMA',
                'name' => 'LIMA',
                'position_x' => 43.22,
                'position_y' => 57.76,
                'color' => '#06B6D4',
                'description' => 'Area pengeboran LIMA. Fasilitas strategis dengan kapasitas produksi optimal di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform LIMA', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '5,700 BOPD',
                'status' => 'Operasional',
                'wells' => 13,
                'depth' => '3,520 m',
                'pressure' => '2,980 psi',
                'temperature' => '90°C',
                'order' => 6,
            ],
            [
                'area_id' => 'KL',
                'name' => 'KL',
                'position_x' => 42.77,
                'position_y' => 65.99,
                'color' => '#84CC16',
                'description' => 'Area pengeboran KL. Lokasi produksi dengan teknologi ramah lingkungan di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform KL', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '4,900 BOPD',
                'status' => 'Operasional',
                'wells' => 10,
                'depth' => '3,280 m',
                'pressure' => '2,720 psi',
                'temperature' => '82°C',
                'order' => 7,
            ],
            [
                'area_id' => 'MB',
                'name' => 'MB',
                'position_x' => 35.71,
                'position_y' => 54.00,
                'color' => '#F97316',
                'description' => 'Area pengeboran MB. Fasilitas produksi dengan sistem keamanan tinggi di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform MB', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '5,300 BOPD',
                'status' => 'Operasional',
                'wells' => 11,
                'depth' => '3,410 m',
                'pressure' => '2,870 psi',
                'temperature' => '87°C',
                'order' => 8,
            ],
            [
                'area_id' => 'ZULU',
                'name' => 'ZULU',
                'position_x' => 6.86,
                'position_y' => 23.37,
                'color' => '#6366F1',
                'description' => 'Area pengeboran ZULU. Lokasi eksplorasi baru dengan potensi cadangan besar di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform ZULU', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '3,800 BOPD',
                'status' => 'Operasional',
                'wells' => 8,
                'depth' => '2,950 m',
                'pressure' => '2,450 psi',
                'temperature' => '72°C',
                'order' => 9,
            ],
            [
                'area_id' => 'PAPA',
                'name' => 'PAPA',
                'position_x' => 25.21,
                'position_y' => 51.95,
                'color' => '#14B8A6',
                'description' => 'Area pengeboran PAPA. Fasilitas terintegrasi dengan sistem distribusi modern di Wilayah Kerja ONWJ.',
                'facilities' => ['Platform PAPA', 'Wellheads', 'Production Facilities', 'Control Room', 'Pipeline System'],
                'production' => '4,600 BOPD',
                'status' => 'Operasional',
                'wells' => 10,
                'depth' => '3,180 m',
                'pressure' => '2,680 psi',
                'temperature' => '80°C',
                'order' => 10,
            ],
        ];

        foreach ($tekkomData as $data) {
            WkTekkom::create($data);
        }
    }
}